[env:esp32-cyd-capacitive]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 748800

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^8.3.11

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -D CORE_DEBUG_LEVEL=1

board_build.partitions = huge_app.csv
extra_scripts = pre:scripts/embed_logo.py

[env:esp32-cyd-capacitive-no-battery]
extends = env:esp32-cyd-capacitive
build_flags =
    ${env:esp32-cyd-capacitive.build_flags}
    -D WLED_CYD_ENABLE_BATTERY=0

[env:macos]
; MacOS simulator
; First, install sdl2 using: brew install sdl2
; Build: pio run -e macos
; Run: .pio/build/macos/program
platform = native
build_type = release

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^8.3.11

build_flags =
    -O0
    -std=c++17
    -lSDL2
    -D LV_CONF_INCLUDE_SIMPLE
    -D WLED_TOUCH_SIMULATOR=1
    -D LGFX_SDL
    -D WLED_CYD_ENABLE_BATTERY=1
    -I include/sim
    -I include
    -I"${sysenv.HOMEBREW_PREFIX}/include/SDL2"
    -L"${sysenv.HOMEBREW_PREFIX}/lib"
    -I"/usr/local/include/SDL2"
    -L"/usr/local/lib"
    -include sim/sdl_prelude.h

build_src_filter =
    +<*>
    -<BatteryMonitor.cpp>

extra_scripts = pre:scripts/embed_logo.py
