[env:esp32-cyd-capacitive]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 748800

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^8.3.11

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -D CORE_DEBUG_LEVEL=1

board_build.partitions = huge_app.csv
extra_scripts = pre:scripts/embed_logo.py

[env:esp32-cyd-capacitive-no-battery]
extends = env:esp32-cyd-capacitive
build_flags =
    ${env:esp32-cyd-capacitive.build_flags}
    -D WLED_CYD_ENABLE_BATTERY=0
