#!/usr/bin/env python3
from pathlib import Path
import os
import subprocess
from typing import Optional

try:
    Import("env")  # type: ignore[name-defined]
except NameError:
    env = None


def project_root() -> Path:
    if env is not None:
        return Path(env.subst("$PROJECT_DIR"))
    return Path(__file__).resolve().parents[1]


def git_output(root: Path, *args: str) -> Optional[str]:
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=root,
            stderr=subprocess.DEVNULL,
        ).strip().decode("utf-8")
    except Exception:
        return None


def normalize_version(version: Optional[str]) -> Optional[str]:
    if not version:
        return None
    version = version.strip()
    if version.startswith("v"):
        version = version[1:]
    return version or None


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_version_header(root: Path) -> str:
    explicit_version = normalize_version(os.environ.get("WLED_TOUCH_VERSION"))
    git_available = git_output(root, "status") is not None

    latest_tag = git_output(root, "describe", "--tags", "--abbrev=0") if git_available else None
    version = explicit_version or normalize_version(latest_tag) or "0.0.0"
    tag = f"v{version}"

    if not git_available:
        git_info = f"{tag} (noGit)"
        git_url = "None"
    else:
        exact_tag = git_output(root, "describe", "--tags", "--exact-match")
        branch = git_output(root, "rev-parse", "--abbrev-ref", "HEAD") or "unknown"
        revision = git_output(root, "rev-parse", "--short", "HEAD") or "unknown"
        modified = git_output(root, "status", "-uno", "-s")
        dirty_files = [
            line for line in (modified or "").splitlines()
            if "include/generated/version.h" not in line
        ]
        dirty = "-dirty" if dirty_files else ""
        git_url = git_output(root, "config", "--get", "remote.origin.url") or "None"

        if exact_tag and normalize_version(exact_tag) == version and not dirty:
            git_info = tag
        else:
            git_info = f"{tag} ({branch}-{revision}{dirty})"

    return f"""#pragma once

// Generated by scripts/git_version.py. Do not edit by hand.

constexpr const char* kAppVersion = "{c_string(version)}";
constexpr const char* kGitInfo = "{c_string(git_info)}";
constexpr const char* kGitUrl = "{c_string(git_url)}";
"""


def main() -> None:
    root = project_root()
    target = root / "include" / "generated" / "version.h"
    content = build_version_header(root)

    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text() != content:
        target.write_text(content)


main()
